from tkinter import *
from tkinter import ttk
main=Tk()
main.title('Login')
main.geometry('1000x700+500+100')
main.resizable(False,False)
main.config(bg='#2E4053')
main.iconbitmap("loginico.ico")
see=Frame(width="390",height="450",bg="#5D6D7E")
see.place(x=300,y=70)
lbl=Label(main,text="Login",font=('Algerian',30),fg="black",bg='#5D6D7E')
lbl.pack(fill=X)
pic=PhotoImage("login.png")
sizepic=pic.subsample(10,10)
tit_pic=Label(see,image=sizepic,bg='#5D6D7E')
tit_pic.place(x=160,y=50)
user=Label(see,text="user",font=('Lucida Calligraphy',22),fg="black",bg='#5D6D7E')
user.place(x=155,y=120)
tapez_user=Entry(see,justify="center",bg='#5D6D7E')
tapez_user.place(x=130,y=160)
password=Label(see,text="password",font=('Lucida Calligraphy',22),fg="black",bg='#5D6D7E')
password.place(x=115,y=200)
tapez_pass=Entry(see,justify="center",bg='#5D6D7E')
tapez_pass.place(x=130,y=240)
pic_log=PhotoImage("log.png")
size_pic_log=pic_log.subsample(2,13)
af_pic=Button(see,image=size_pic_log,bg='#5D6D7E')
af_pic.place(x=66,y=300)
sign=Button(see,text='Sing Up',bg='#5D6D7E',fg="white")
sign.place(x=160,y=370)
main.mainloop()
